var fullMacroData = {
    "contributors": ["ezmna59", "zetex", "watersquarez", "Toster", "alex", "NotBelugaFan", "Vinsterplayz", "Vibri", "sear", "C00L", "Fuyu", "dudodo", "Zettaminx"],
    "difficulties": ["NA", "Auto", "Easy", "Normal", "Hard", "Hard", "Harder", "Harder", "Insane", "Insane", "Easy Demon", "Medium Demon", "Hard Demon", "Insane Demon", "Extreme Demon", "No Victors (ILL)"],
    "ratings": ["Unrated", "Rated", "Featured", "Epic", "Legendary", "Mythic"],
    "ill": ["candy-crush-buff","permafrost-peaks"],
    "macros": [
        {
            "id": "brr",
            "name": "BRRRRRRRRRRRR",
            "creator": "Wolvyy",
            "levelid": "97642383",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 4,
            "bot": ["ybot"],
            "time": 5.620,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": "Level is known for being hilariously fast. This time cannot be achieved on the leaderboards due to the anticheat removing times under 10 seconds."
        },
        {
            "id": "permafrost-peaks",
            "name": "Permafrost Peaks",
            "creator": "xnu",
            "levelid": "98852405",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 15,
            "bot": ["ybot"],
            "time": 8.179,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/-GwMwRCvca8",
            "download": true,
            "desc": "Macro broken, press left on frame 0 to align"
        },
        {
            "id": "yiik-a-postalbertrpg",
            "name": "YiiK A PostAlbertRPG",
            "creator": "joeingly",
            "levelid": "100353881",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["mhr"],
            "time": 9.275,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/IZdQ36AW9zA",
            "download": true,
            "desc": false
        },
        {
            "id": "venus",
            "name": "VENUS",
            "creator": "DrakXD109",
            "levelid": "97524369",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 9.562,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/VALsq5kBlKA",
            "download": true,
            "desc": false
        },
        {
            "id": "sunken-pier",
            "name": "Sunken Pier",
            "creator": "Nyan Cat",
            "levelid": "97534859",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 9.900,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/i3qL9yFt1q0",
            "download": true,
            "desc": false
        },
        {
            "id": "infinity-trial",
            "name": "Infinity Trial",
            "creator": "DrakXD109",
            "levelid": "99978836",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 10.445,
            "tps": 240,
            "contributor": "sear",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/jldYyXEtasY",
            "download": true,
            "desc": "by likegg & more"
        },
        {
            "id": "square-keys",
            "name": "Square keys",
            "creator": "Daminusoff",
            "levelid": "101007574",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 3,
            "bot": ["ybot"],
            "time": 11.287,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/hZQjH8BF894",
            "download": true,
            "desc": false
        },
        {
            "id": "bimba-y-lola",
            "name": "Bimba y Lola",
            "creator": "heda",
            "levelid": "97704668",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 7,
            "bot": ["ybot"],
            "time": 13.058,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.2,
            "video": false,
            "download": true,
            "desc": "How did this get rated lol"
        },
        {
            "id": "wendys-revenge",
            "name": "Wendys Revenge",
            "creator": "hoshyvention",
            "levelid": "97687438",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 13.795,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "tetris-in-gd",
            "name": "Tetris in GD",
            "creator": "whawhaf",
            "levelid": "98867410",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 7,
            "bot": ["ybot"],
            "time": 13.979,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/iXbfgD9iXHw",
            "download": false,
            "desc": "RNG Manipulation used here, so it won't work on the original level. Needs modification to get only long pieces"
        },
        {
            "id": "ruined",
            "name": "Ruined",
            "creator": "erzor",
            "levelid": "97930264",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 15,
            "bot": ["ybot"],
            "time": 14.412,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/Qph12gXkUx0",
            "download": true,
            "desc": "Macro broken, press left on frame 0 to align"
        },
        {
            "id": "candy-crush-buff",
            "name": "Candy Crush buff",
            "creator": "nhauqq",
            "levelid": "98714164",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 15,
            "bot": ["ybot"],
            "time": 14.529,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/qQbuAFyYp6U",
            "download": true,
            "desc": "Hardest level on the Impossible Platformer List."
        },
        {
            "id": "shimmering-sierra",
            "name": "Shimmering Sierra",
            "creator": "super79",
            "levelid": "97627454",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 6,
            "bot": ["ybot"],
            "time": 15.275,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": "Used to be one of the 5 fastest rated levels."
        },
        {
            "id": "scarlet-basement",
            "name": "Scarlet Basement",
            "creator": "mudspud",
            "levelid": "97543818",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 15.466,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/VhwNPuxVYLo",
            "download": true,
            "desc": false
        },
        {
            "id": "transformative-area",
            "name": "Transformative Area",
            "creator": "xetto",
            "levelid": "97676478",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 4,
            "bot": ["ybot"],
            "time": 15.679,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": "Used to be one of the 5 fastest rated levels."
        },
        {
            "id": "get-the-apple",
            "name": "Get The Apple",
            "creator": "wRubix",
            "levelid": "97596839",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 5,
            "bot": ["ybot"],
            "time": 16.458,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "the-tower-xxii",
            "name": "The Tower XXII",
            "creator": "o1iv3",
            "levelid": "97692058",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 16.633,
            "tps": 240,
            "contributor": "sear",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/gLTLb2bsEls",
            "download": true,
            "desc": "Was once the hardest rated platformer level."
        },
        {
            "id": "getting-over-it",
            "name": "Getting Over It",
            "creator": "TheFakeTJ",
            "levelid": "97480163",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 8,
            "bot": ["ybot"],
            "time": 16.991,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.203,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "spartan-tower",
            "name": "Spartan Tower",
            "creator": "Raivolt",
            "levelid": "97614556",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 9,
            "bot": ["ybot"],
            "time": 17.147,
            "tps": 240,
            "contributor": "zetex",
            "version": 2.2,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "climb",
            "name": "climb",
            "creator": "UsteX",
            "levelid": "98881216",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 3,
            "bot": ["ybot"],
            "time": 17.700,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "snowy-peaks",
            "name": "Snowy Peaks",
            "creator": "FLVRE",
            "levelid": "97943343",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 4,
            "bot": ["ybot"],
            "time": 19.541,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.2,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "i-wanna-be-the-cry",
            "name": "I WANNA BE THE CRY",
            "creator": "DrakXD109",
            "levelid": "100424146",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 18.975,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/UhP3qxDpJt0",
            "download": false,
            "desc": false
        },
        {
            "id": "eternal-ending",
            "name": "ETERNAL ENDING",
            "creator": "No ob",
            "levelid": "98316946",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 20.675,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/zQn3oTlEHgw",
            "download": true,
            "desc": false
        },
        {
            "id": "citadel-climb",
            "name": "Citadel Climb",
            "creator": "imbaz",
            "levelid": "97627452",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 8,
            "bot": ["ybot"],
            "time": 20.649,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "ftrial",
            "name": "ftrial",
            "creator": "DrakXD109",
            "levelid": "97570694",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 21.270,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/f3gmwzK-Qdc",
            "download": true,
            "desc": false
        },
        {
            "id": "disco-dungeon",
            "name": "Disco Dungeon",
            "creator": "ewop",
            "levelid": "97638770",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 2,
            "bot": ["ybot"],
            "time": 21.845,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "ancient",
            "name": "Ancient",
            "creator": "ameraldy",
            "levelid": "97818880",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 4,
            "bot": ["ybot"],
            "time": 22.370,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.2,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "infinity-trials",
            "name": "Infinity Trials",
            "creator": "ninzwz",
            "levelid": "97730554",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 22.175,
            "tps": 240,
            "contributor": "sear",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/JMDWzpBMdNk",
            "download": true,
            "desc": false
        },
        {
            "id": "smelvin-teahouse",
            "name": "Smelvin Teahouse",
            "creator": "Raivolt",
            "levelid": "97949737",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 22.625,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/wgvtANMTC6w",
            "download": true,
            "desc": false
        },
        {
            "id": "smblv1",
            "name": "Super Mario Bros Lv1",
            "creator": "zejoant",
            "levelid": "97978413",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 3,
            "bot": ["ybot"],
            "time": 22.650,
            "tps": 240,
            "contributor": "C00L",
            "version": 2.202,
            "video": "https://www.youtube.com/embed/mwpsSyQu9oY",
            "download": false,
            "desc": false
        },
        {
            "id": "shiftleaf-temple",
            "name": "ShiftLeaf Temple",
            "creator": "trideapthbear",
            "levelid": "98079761",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 10,
            "bot": ["ybot"],
            "time": 22.825,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.203,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "launch-factory",
            "name": "Launch Factory",
            "creator": "Manix648",
            "levelid": "97978413",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 13,
            "bot": ["ybot"],
            "time": 24.600,
            "tps": 240,
            "contributor": "ezmna59",
            "version": 2.202,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "the-old-tower",
            "name": "The Old Tower",
            "creator": "b4pro",
            "levelid": "97749804",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 7,
            "bot": ["ybot"],
            "time": 25.475,
            "tps": 240,
            "contributor": "ezmna59",
            "version": 2.202,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "chromaside",
            "name": "Chromaside",
            "creator": "qalli",
            "levelid": "97793375",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 13,
            "bot": ["ybot"],
            "time": 25.883,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/sAum6cTWn2w",
            "download": true,
            "desc": "Thanks to Alex for creating a TAS first, this wouldn't be possible without him"
        },
        {
            "id": "cascade-crypts",
            "name": "Cascade Crypts",
            "creator": "Nascense",
            "levelid": "97566507",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 6,
            "bot": ["ybot"],
            "time": 26.995,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.202,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "squid-game-font",
            "name": "Squid game font",
            "creator": "cw2003 GB",
            "levelid": "97663296",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 5,
            "bot": ["ybot"],
            "time": 28.379,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "a-true-city",
            "name": "A True City",
            "creator": "Foliblox",
            "levelid": "97589231",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 6,
            "bot": ["ybot"],
            "time": 29.854,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/Xm_VmjXUrlY",
            "download": true,
            "desc": "One of the first rated platformers. Thanks to Alex for creating a TAS first, I used it to help me make this one. 30.1x probably possible"
        },
        {
            "id": "the-golden-tower",
            "name": "The Golden Tower",
            "creator": "BridgetTheCroco",
            "levelid": "97698751",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 2,
            "bot": ["ybot","mhr"],
            "time": 30.458,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/GXHzF-mEdzg",
            "download": true,
            "desc": "Alignment bug, press left on frame 0"
        },
        {
            "id": "cobblestone-crypts",
            "name": "Cobblestone Crypts",
            "creator": "InfernoZXV",
            "levelid": "97972420",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 5,
            "bot": ["ybot"],
            "time": 32.391,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "a-christmas-delivery",
            "name": "A Christmas Delivery",
            "creator": "CamZam",
            "levelid": "97603989",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 2,
            "bot": ["ybot"],
            "time": 37.220,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/EAADEDbYG5I",
            "download": true,
            "desc": false
        },
        {
            "id": "i-wanna-be-the-guy",
            "name": "I wanna be the guy",
            "creator": "Aless50",
            "levelid": "97543536",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 13,
            "bot": ["ybot"],
            "time": 38.625,
            "tps": 240,
            "contributor": "sear",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/KbG2zHc2P30",
            "download": true,
            "desc": false
        },
        {
            "id": "jet-lag",
            "name": "Jet Lag",
            "creator": "disp",
            "levelid": "97536552",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 11,
            "bot": ["ybot"],
            "time": 43.450,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/O07leRTPjLI",
            "download": true,
            "desc": "First rated platformer demon."
        },
        {
            "id": "sunset-summit",
            "name": "Sunset Summit",
            "creator": "ScriptedNil",
            "levelid": "98094285",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 12,
            "bot": ["ybot"],
            "time": 44.336,
            "tps": 240,
            "contributor": "sear",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "impossible-boy",
            "name": "Impossible Boy",
            "creator": "Romlekt",
            "levelid": "98011217",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 48.587,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/6S8jzN_2vGA",
            "download": true,
            "desc": false
        },
        {
            "id": "spidertek",
            "name": "Spidertek",
            "creator": "OWOSI",
            "levelid": "101116471",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 11,
            "bot": ["ybot"],
            "time": 49.012,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "enjoying-the-sun",
            "name": "Enjoying The Sun",
            "creator": "AutoNick",
            "levelid": "97459884",
            "mode": "platformer",
            "rating": 3,
            "difficulty": 5,
            "bot": ["ybot"],
            "time": 50.037,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": "Doesn't always work due to randomness in the dungeon part"
        },
        {
            "id": "dashing-over-it",
            "name": "Dashing Over It",
            "creator": "Halapeenyo",
            "levelid": "98695499",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 11,
            "bot": ["ybot"],
            "time": 54.579,
            "tps": 240,
            "contributor": "ezmna59",
            "version": 2.202,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "dash-cave",
            "name": "Dash Cave",
            "creator": "Booglee",
            "levelid": "98128088",
            "mode": "platformer",
            "rating": 3,
            "difficulty": 4,       
            "bot": ["ybot"],
            "time": 54.920,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": "Missing a skip. Will redo eventually."
        },
        {
            "id": "bramble-scramble",
            "name": "Bramble Scramble",
            "creator": "Crerro",
            "levelid": "99126990",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 58.175,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/6S8jzN_2vGA",
            "download": true,
            "desc": false
        },
        {
            "id": "forsaken-city",
            "name": "Forsaken City",
            "creator": "LightPotato99",
            "levelid": "97906220",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 10,
            "bot": ["ybot"],
            "time": 58.716,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/yFoqweo2exo",
            "download": true,
            "desc": false
        },
        {
            "id": "flipswap-factory",
            "name": "Flipswap Factory",
            "creator": "zejoant",
            "levelid": "98439428",
            "mode": "platformer",
            "rating": 3,
            "difficulty": 11,
            "bot": ["ybot"],
            "time": 59.975,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/V2ewGtogoeM",
            "download": true,
            "desc": false
        },
        {
            "id": "loco-motive",
            "name": "Loco Motive",
            "creator": "Subwoofer",
            "levelid": "97598449",
            "mode": "platformer",
            "rating": 3,
            "difficulty": 6,
            "bot": ["ybot"],
            "time": 60.087,
            "tps": 240,
            "contributor": "ezmna59",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "silent-hills",
            "name": "Silent Hills",
            "creator": "walterberg",
            "levelid": "101269702",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 62.466,
            "tps": 240,
            "contributor": "sear",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/Ng62-N0wWz8",
            "download": true,
            "desc": false
        },
        {
            "id": "infiltration",
            "name": "Infiltration",
            "creator": "KingEggplant987",
            "levelid": "101619476",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 10,
            "bot": ["ybot"],
            "time": 63.391,
            "tps": 240,
            "contributor": "Zettaminx",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/CAd2mDzTgSQ",
            "download": true,
            "desc": false
        },
        {
            "id": "tower",
            "name": "The Tower",
            "creator": "RobTop",
            "levelid": "5001",
            "mode": "platformer",
            "rating": -1,
            "difficulty": 5,
            "bot": ["ybot"],
            "time": 64.875,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": "Any%. One of the most optimized TASes. Many people worked to find strategies for the main levels"
        },
        {
            "id": "dualist",
            "name": "duAlist",
            "creator": "KingEggplant987",
            "levelid": "98457659",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 12,
            "bot": ["ybot"],
            "time": 65.729,
            "tps": 240,
            "contributor": "Vinsterplays",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/Uqm_boHevLg" ,
            "download": false,
            "desc": false
        },
        {
            "id": "blink-blink-blink",
            "name": "Blink Blink Blink",
            "creator": "GDTicLos",
            "levelid": "97910997",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 8,
            "bot": ["ybot"],
            "time": 68.025,
            "tps": 240,
            "contributor": "Toster",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "subterranean-odyssey",
            "name": "Subterranean Odyssey",
            "creator": "Woxius",
            "levelid": "100513599",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 5,
            "bot": ["ybot"],
            "time": 69.591,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "tower-100",
            "name": "The Tower (100%)",
            "creator": "RobTop",
            "levelid": "5001",
            "mode": "platformer",
            "rating": -1,
            "difficulty": 5,
            "bot": ["mhr"],
            "time": 71.516,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/vKeSCcIexhc",
            "download": true,
            "desc": "One of the most optimized TASes. Many people worked to find strategies for the main levels"
        },
        {
            "id": "sewers",
            "name": "The Sewers",
            "creator": "RobTop",
            "levelid": "5002",
            "mode": "platformer",
            "rating": -1,
            "difficulty": 6,
            "bot": ["ybot"],
            "time": 72.279,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": "One of the most optimized TASes. Many people worked to find strategies for the main levels."
        },
        {
            "id": "cellar",
            "name": "The Cellar",
            "creator": "RobTop",
            "levelid": "5003",
            "mode": "platformer",
            "rating": -1,
            "difficulty": 7,
            "bot": ["ybot"],
            "time": 76.429,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/q7KeJFryZjI",
            "download": true,
            "desc": "One of the most optimized TASes. Many people worked to find strategies for the main levels."
        },
        {
            "id": "beneath-the-bouncer",
            "name": "Beneath The Bouncer",
            "creator": "Und3rcov3r",
            "levelid": "97701937",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 3,
            "bot": ["ybot"],
            "time": 82.137,
            "tps": 240,
            "contributor": "Zettaminx",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "hexagon-force",
            "name": "Hexagon Force",
            "creator": "RobTop",
            "levelid": "16",
            "mode": "classic",
            "rating": -1,
            "difficulty": 9,
            "bot": ["mhr","ybot"],
            "time": 82.30,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "pseudo-zone",
            "name": "Pseudo Zone",
            "creator": "NinKaz",
            "levelid": "99110853",
            "mode": "platformer",
            "rating": 3,
            "difficulty": 6,
            "bot": ["ybot"],
            "time": 84.779,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/wxgFvhChfVw",
            "download": true,
            "desc": false
        },
        {
            "id": "dash",
            "name": "Dash",
            "creator": "RobTop",
            "levelid": "22",
            "mode": "classic",
            "rating": -1,
            "difficulty": 9,
            "bot": ["ybot","mhr"],
            "time": 85.77,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/Ir2gPqjhX7U",
            "download": true,
            "desc": false
        },
        {
            "id": "cellar-100",
            "name": "The Cellar (100%)",
            "creator": "RobTop",
            "levelid": "5003",
            "mode": "platformer",
            "rating": -1,
            "difficulty": 7,
            "bot": ["mhr"],
            "time": 88.033,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/vKeSCcIexhc?start=179",
            "download": true,
            "desc": "One of the most optimized TASes. Many people worked to find strategies for the main levels."
        },
        {
            "id": "terminal-heaven",
            "name": "Terminal Heaven",
            "creator": "G4lvatron",
            "levelid": "99335322",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 88.699,
            "tps": 240,
            "contributor": "Vinsterplays",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/0WBmGtWY0dg",
            "download": false,
            "desc": false
        },
        {
            "id": "sewers-100",
            "name": "The Sewers (100%)",
            "creator": "RobTop",
            "levelid": "5002",
            "mode": "platformer",
            "rating": -1,
            "difficulty": 6,
            "bot": ["mhr"],
            "time": 89.583,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/vKeSCcIexhc?start=80",
            "download": true,
            "desc": "One of the most optimized TASes. Many people worked to find strategies for the main levels."
        },
        {
            "id": "deadlocked",
            "name": "Deadlocked",
            "creator": "RobTop",
            "levelid": "20",
            "mode": "classic",
            "rating": -1,
            "difficulty": 10,
            "bot": ["mhr","ybot"],
            "time": 98.39,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": "Saves ~0.16s vs regular completion."
        },
        {
            "id": "i-wanna-beat-acheron",
            "name": "IWannaBeatAcheron",
            "creator": "Aless50",
            "levelid": "98011217",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 102.158,
            "tps": 360,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/pDyRCzjzaek",
            "download": true,
            "desc": "360 TPS. Kinda broken, press left briefly before it starts to align."
        },
        {
            "id": "coaster-mountain",
            "name": "Coaster Mountain",
            "creator": "Serponge",
            "levelid": "98170000",
            "mode": "platformer",
            "rating": 4,
            "difficulty": 11,
            "bot": ["ybot"],
            "time": 102.862,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "old-site-gdside",
            "name": "old site gdside",
            "creator": "ArcadiacManiac",
            "levelid": "98147815",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 11,
            "bot": ["ybot"],
            "time": 105.220,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/KK6NABvWFQU",
            "download": true,
            "desc": false
        },
        {
            "id": "robot-king",
            "name": "Robot King",
            "creator": "GDgalaxygaming",
            "levelid": "99927952",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 109.512,
            "tps": 240,
            "contributor": "sear",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/B1MSp8whwWc",
            "download": true,
            "desc": false
        },
        {
            "id": "tower-of-infinity",
            "name": "Tower of Infinity",
            "creator": "zYuko",
            "levelid": "97713011",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 117.55,
            "tps": 240,
            "contributor": "alex",
            "version": 2.2,
            "video": "https://www.youtube.com/embed/6QDSF_9Nr9A",
            "download": false,
            "desc": false
        },
        {
            "id": "patio-light",
            "name": "Patio Light",
            "creator": "KEaliTgeo",
            "levelid": "99701334",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 14,   
            "bot": ["mhr"],
            "time": 118.679,
            "tps": 240,
            "contributor": "LucaGoku",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/Vz4wgBbApik&t=71s",
            "download": true,
            "desc": false
        },
        {
            "id": "22-trials-of-pain",
            "name": "22 Trials of PAIN",
            "creator": "sink",
            "levelid": "98228276",
            "mode": "platformer",
            "rating": 2,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 122.079,
            "tps": 240,
            "contributor": "Fuyu",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/hklgxBLOk0A",
            "download": true,
            "desc": false
        },
        {
            "id": "tower-of-rage",
            "name": "Tower of Rage",
            "creator": "Nontypical",
            "levelid": "100782112",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 10,
            "bot": ["ybot"],
            "time": 141.637,
            "tps": 240,
            "contributor": "Zettaminx",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/AuwXkIkWUeE",
            "download": true,
            "desc": false
        },
        {
            "id": "i-made-this-level",
            "name": "I Made This Level",
            "creator": "npesta",
            "levelid": "97956692",
            "mode": "platformer",
            "rating": 0,
            "difficulty": 12,
            "bot": ["ybot"],
            "time": 141.897,
            "tps": 240,
            "contributor": "alex",
            "version": 2.2,
            "video": "https://www.youtube.com/embed/0RjtZo00ELI",
            "download": false,
            "desc": false
        },
        {
            "id": "baddie-castle",
            "name": "Baddie Castle",
            "creator": "TropoGD",
            "levelid": "97809320",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 3,
            "bot": ["ybot"],
            "time": 142.050,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/wUg7RZ95wsQ",
            "download": true,
            "desc": false
        },
        {
            "id": "gd-tower-tiny-square",
            "name": "GD Tower Tiny Square",
            "creator": "liamiamliam",
            "levelid": "98489186",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 12,
            "bot": ["ybot"],
            "time": 151.858,
            "tps": 240,
            "contributor": "Vibri",
            "version": 2.202,
            "video": false,
            "download": true,
            "desc": false
        },
        {
            "id": "tornado",
            "name": "Tornado",
            "creator": "AbstractDark",
            "levelid": "101624652",
            "mode": "platformer",
            "rating": 4,
            "difficulty": 6,
            "bot": ["ybot","mhr"],
            "time": 161.916,
            "tps": 240,
            "contributor": "ShadowyZephyr",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/1rap_a7YyPQ",
            "download": true,
            "desc": false
        },
        {
            "id": "the-abyss",
            "name": "The Abyss",
            "creator": "zYuko",
            "levelid": "98163412",
            "mode": "platformer",
            "rating": 1,
            "difficulty": 14,
            "bot": ["ybot"],
            "time": 381.912,
            "tps": 240,
            "contributor": "sear, erzor",
            "version": 2.204,
            "video": "https://www.youtube.com/embed/vGiwAgO6mpo",
            "download": true,
            "desc": false
        }
    ]
}